### PR TITLE
My new commit to AutomobileGallery website

### PR DESCRIPTION
**Pull request by dayanand-g**
Hey there,

As you said am commited new code to the branch dy, so please kindly merge my code into it.

Thank you..

### CODE REVIEW

**Comment by dayanand-g** [comment]
Please give access to this branch so I can clear all the conflicts.

**Comment by dayanand-g** [comment]
Or it is not possible to give an access for me, please you can give an opportunity to create a another new branch so I can resolve all the conflicts there and I can push my code into it.
Thank you..

**Comment by Yadvendra7** [comment]
not to worry , due to some technical anomalies , we couldn't resolve the conflicts between two assignees , will come with a solution . apologies for inconvenience.

**Comment by Yadvendra7** [comment]
@Pratyush-Saxena sir i request you to pls look into this

**Comment by dayanand-g** [comment]
Yeah sure sir I looked into it and I know that were am wrong, It's not your problem, so if you don't mind can I create a another branch and push my code into it.
I can push the code with No conflicts sir.
So please give permission to create a another PR.

Thank you..

**Comment by s-pratyush** [comment]
> Yeah sure sir I looked into it and I know that were am wrong, It's not your problem, so if you don't mind can I create a another branch and push my code into it. I can push the code with No conflicts sir. So please give permission to create a another PR.
> 
> Thank you..

well you can resolve this conflict without creating new branch , just take a fresh pull and then in ur IDE (prefer vs code)  it will ask you to make choice which changes you want to keep .

**Comment by dayanand-g** [comment]
Sorry sir It can't be done in the same branch itself coz the branch is created by your side and the resolve conflicts option is not available for me in the github itself and am able to clear all the conflicts in the  github itself, So if you give an permission to create a another branch i will do it sir.

**Comment by Yadvendra7** [comment]
Dear @dayanand-g  We have assigned you the issue and now it's possible for you to create your own branch and merge your files in that branch.
@Pratyush-Saxena will guide you incase there is any issue .
All the best !

**Review by Yadvendra7 — APPROVED** [review]
Great

**Comment by anuj108** [comment]
@dayanand-g try pushing your code on the new branch 'dev'.

**Pull request closed without merging**
